// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2mqA18vU3vkpw8fmHw7GP9
// Component: hGw_PBzTluaE
import * as React from "react";
import Head from "next/head";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_kartik_portfolio.module.css"; // plasmic-import: 2mqA18vU3vkpw8fmHw7GP9/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: hGw_PBzTluaE/css
import Basketball1Icon from "./icons/PlasmicIcon__Basketball1"; // plasmic-import: vdXgM7ScCMI/icon
import GroupIcon from "./icons/PlasmicIcon__Group"; // plasmic-import: DcB5oEDtQz9/icon
import Group191Icon from "./icons/PlasmicIcon__Group191"; // plasmic-import: znruXwAJg96/icon
import Line104Icon from "./icons/PlasmicIcon__Line104"; // plasmic-import: 0BWX4kgY0fD/icon
import Ellipse166Icon from "./icons/PlasmicIcon__Ellipse166"; // plasmic-import: rJWeaOL-dq5/icon
import Ellipse167Icon from "./icons/PlasmicIcon__Ellipse167"; // plasmic-import: DnxiLItfZc1/icon
import Ellipse168Icon from "./icons/PlasmicIcon__Ellipse168"; // plasmic-import: uv1e117DCtO/icon
import Vector38Icon from "./icons/PlasmicIcon__Vector38"; // plasmic-import: T7cvxSOaM6/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <React.Fragment>
      <Head>
        <title key="title">{""}</title>
        <meta key="og:title" property="og:title" content={""} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"section1"}
            data-plasmic-override={overrides.section1}
            className={classNames(defaultcss.all, sty.section1)}
          >
            {false ? (
              <div
                data-plasmic-name={"rectangle419"}
                data-plasmic-override={overrides.rectangle419}
                className={classNames(defaultcss.all, sty.rectangle419)}
              />
            ) : null}
            {false ? (
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__uUbgj)}
                role={"img"}
                src={"/plasmic/kartik_portfolio/images/ellipse165.svg"}
              />
            ) : null}

            <div
              data-plasmic-name={"_2D406C1010845191"}
              data-plasmic-override={overrides._2D406C1010845191}
              className={classNames(defaultcss.all, sty._2D406C1010845191)}
            />

            <div
              data-plasmic-name={"helloImMarlonSimonUxUiDesigner"}
              data-plasmic-override={overrides.helloImMarlonSimonUxUiDesigner}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.helloImMarlonSimonUxUiDesigner
              )}
            >
              {"Hello,I'm\r\nMarlon Simon\r\nUX-UI Designer\n"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__nYkuy
              )}
            >
              {"Marsi."}
            </div>

            <div
              data-plasmic-name={"group192"}
              data-plasmic-override={overrides.group192}
              className={classNames(defaultcss.all, sty.group192)}
            >
              <div
                data-plasmic-name={"dribbleBehince"}
                data-plasmic-override={overrides.dribbleBehince}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.dribbleBehince
                )}
              >
                {"Dribble                 Behince "}
              </div>

              <Basketball1Icon
                className={classNames(defaultcss.all, sty.svg__giUb)}
                role={"img"}
              />

              <div
                data-plasmic-name={"behance1"}
                data-plasmic-override={overrides.behance1}
                className={classNames(defaultcss.all, sty.behance1)}
              >
                <div
                  data-plasmic-name={"group"}
                  data-plasmic-override={overrides.group}
                  className={classNames(defaultcss.all, sty.group)}
                >
                  <div
                    data-plasmic-name={"group2"}
                    data-plasmic-override={overrides.group2}
                    className={classNames(defaultcss.all, sty.group2)}
                  >
                    <GroupIcon
                      className={classNames(defaultcss.all, sty.svg___3L4J)}
                      role={"img"}
                    />
                  </div>
                </div>
              </div>
            </div>

            <Group191Icon
              className={classNames(defaultcss.all, sty.svg__tXmsa)}
              role={"img"}
            />

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__idHw
              )}
            >
              {"Download Resum"}
            </div>

            <Line104Icon
              className={classNames(defaultcss.all, sty.svg__zyybo)}
              role={"img"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__zdrIx)}
              role={"img"}
              src={"/plasmic/kartik_portfolio/images/cube1.svg"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__xiJfk)}
              role={"img"}
              src={"/plasmic/kartik_portfolio/images/cube2.svg"}
            />

            <img
              alt={""}
              className={classNames(defaultcss.img, sty.img__hbOwn)}
              role={"img"}
              src={"/plasmic/kartik_portfolio/images/cube3.svg"}
            />

            <div
              data-plasmic-name={"group193"}
              data-plasmic-override={overrides.group193}
              className={classNames(defaultcss.all, sty.group193)}
            >
              <Ellipse166Icon
                className={classNames(defaultcss.all, sty.svg__lf3K)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle420"}
                data-plasmic-override={overrides.rectangle420}
                className={classNames(defaultcss.all, sty.rectangle420)}
              />
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qk76X
              )}
            >
              {"Scrol Down"}
            </div>

            <Ellipse167Icon
              className={classNames(defaultcss.all, sty.svg__rCokL)}
              role={"img"}
            />

            <Ellipse168Icon
              className={classNames(defaultcss.all, sty.svg__yYPpN)}
              role={"img"}
            />
          </div>

          <div
            data-plasmic-name={"section2"}
            data-plasmic-override={overrides.section2}
            className={classNames(defaultcss.all, sty.section2)}
          >
            <div
              data-plasmic-name={"rectangle421"}
              data-plasmic-override={overrides.rectangle421}
              className={classNames(defaultcss.all, sty.rectangle421)}
            />

            <div
              data-plasmic-name={"rectangle422"}
              data-plasmic-override={overrides.rectangle422}
              className={classNames(defaultcss.all, sty.rectangle422)}
            />

            <div
              data-plasmic-name={"newsletter"}
              data-plasmic-override={overrides.newsletter}
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.newsletter
              )}
            >
              {"Newsletter\r\n"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__xE1H8
              )}
            >
              {
                "Mauris aliquet egestas metus, \nid pellentesque mauris tincidunt."
              }
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__h052D
              )}
            >
              {"Enter Your mail"}
            </div>

            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__qngPc
              )}
            >
              {"Subcrib Now"}
            </div>

            <Vector38Icon
              className={classNames(defaultcss.all, sty.svg__q7Mo)}
              role={"img"}
            />

            <Vector38Icon
              className={classNames(defaultcss.all, sty.svg__fKhIw)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "section1",
    "rectangle419",
    "_2D406C1010845191",
    "helloImMarlonSimonUxUiDesigner",
    "group192",
    "dribbleBehince",
    "behance1",
    "group",
    "group2",
    "group193",
    "rectangle420",
    "section2",
    "rectangle421",
    "rectangle422",
    "newsletter"
  ],

  section1: [
    "section1",
    "rectangle419",
    "_2D406C1010845191",
    "helloImMarlonSimonUxUiDesigner",
    "group192",
    "dribbleBehince",
    "behance1",
    "group",
    "group2",
    "group193",
    "rectangle420"
  ],

  rectangle419: ["rectangle419"],
  _2D406C1010845191: ["_2D406C1010845191"],
  helloImMarlonSimonUxUiDesigner: ["helloImMarlonSimonUxUiDesigner"],
  group192: ["group192", "dribbleBehince", "behance1", "group", "group2"],
  dribbleBehince: ["dribbleBehince"],
  behance1: ["behance1", "group", "group2"],
  group: ["group", "group2"],
  group2: ["group2"],
  group193: ["group193", "rectangle420"],
  rectangle420: ["rectangle420"],
  section2: ["section2", "rectangle421", "rectangle422", "newsletter"],
  rectangle421: ["rectangle421"],
  rectangle422: ["rectangle422"],
  newsletter: ["newsletter"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section1: makeNodeComponent("section1"),
    rectangle419: makeNodeComponent("rectangle419"),
    _2D406C1010845191: makeNodeComponent("_2D406C1010845191"),
    helloImMarlonSimonUxUiDesigner: makeNodeComponent(
      "helloImMarlonSimonUxUiDesigner"
    ),

    group192: makeNodeComponent("group192"),
    dribbleBehince: makeNodeComponent("dribbleBehince"),
    behance1: makeNodeComponent("behance1"),
    group: makeNodeComponent("group"),
    group2: makeNodeComponent("group2"),
    group193: makeNodeComponent("group193"),
    rectangle420: makeNodeComponent("rectangle420"),
    section2: makeNodeComponent("section2"),
    rectangle421: makeNodeComponent("rectangle421"),
    rectangle422: makeNodeComponent("rectangle422"),
    newsletter: makeNodeComponent("newsletter"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
