// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2mqA18vU3vkpw8fmHw7GP9
// Component: K8JtqehUC4
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_kartik_portfolio.module.css"; // plasmic-import: 2mqA18vU3vkpw8fmHw7GP9/projectcss
import * as sty from "./PlasmicHeroLink.module.css"; // plasmic-import: K8JtqehUC4/css

export const PlasmicHeroLink__VariantProps = new Array();

export const PlasmicHeroLink__ArgProps = new Array();

function PlasmicHeroLink__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Download Resume"}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeroLink__ArgProps,
      internalVariantPropNames: PlasmicHeroLink__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHeroLink__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeroLink";
  } else {
    func.displayName = `PlasmicHeroLink.${nodeName}`;
  }
  return func;
}

export const PlasmicHeroLink = Object.assign(
  // Top-level PlasmicHeroLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicHeroLink
    internalVariantProps: PlasmicHeroLink__VariantProps,
    internalArgProps: PlasmicHeroLink__ArgProps
  }
);

export default PlasmicHeroLink;
/* prettier-ignore-end */
