// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2mqA18vU3vkpw8fmHw7GP9
// Component: NP_waT9R6b
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_kartik_portfolio.module.css"; // plasmic-import: 2mqA18vU3vkpw8fmHw7GP9/projectcss
import * as sty from "./PlasmicHeroTitle.module.css"; // plasmic-import: NP_waT9R6b/css

export const PlasmicHeroTitle__VariantProps = new Array();

export const PlasmicHeroTitle__ArgProps = new Array();

function PlasmicHeroTitle__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.root
      )}
    >
      {"Hello,I'm\r\nKartik Sorathiya\nUX-UI Designer\n"}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeroTitle__ArgProps,
      internalVariantPropNames: PlasmicHeroTitle__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHeroTitle__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeroTitle";
  } else {
    func.displayName = `PlasmicHeroTitle.${nodeName}`;
  }
  return func;
}

export const PlasmicHeroTitle = Object.assign(
  // Top-level PlasmicHeroTitle renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicHeroTitle
    internalVariantProps: PlasmicHeroTitle__VariantProps,
    internalArgProps: PlasmicHeroTitle__ArgProps
  }
);

export default PlasmicHeroTitle;
/* prettier-ignore-end */
